source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Ursmilesforadvisor' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', path: '../node_modules/react-native', :subspecs => [
                                                                 'Core',
                                                                 'RCTActionSheet',
                                                                 'RCTAnimation',
                                                                 'RCTGeolocation',
                                                                 'RCTImage',
                                                                 'RCTLinkingIOS',
                                                                 'RCTNetwork',
                                                                 'RCTSettings',
                                                                 'RCTText',
                                                                 'RCTVibration',
                                                                 'RCTWebSocket',
                                                                 'DevSupport'
                                                                 ]
pod 'Fabric'
pod 'Crashlytics', '~> 3.10'
#   pod 'Firebase/Core'

pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'Interactable', :path => '../node_modules/react-native-interactable'

pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

end

post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == "react-native-google-maps"
target.build_configurations.each do |config|
config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
end
end
if target.name == "React"
target.remove_from_project
end
end
end

